// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwAC_SWw4ICXyMrIWJE14J9KOdKjDc620',
    appId: '1:148369501195:web:0fedd3cdb587223ce16b0e',
    messagingSenderId: '148369501195',
    projectId: 'finanzas-d8536',
    authDomain: 'finanzas-d8536.firebaseapp.com',
    databaseURL: 'https://finanzas-d8536-default-rtdb.firebaseio.com',
    storageBucket: 'finanzas-d8536.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0nj_CQsUGE4jMt1Q7chBJ33TaZRyhxJ4',
    appId: '1:148369501195:android:99a19dbe57100a72e16b0e',
    messagingSenderId: '148369501195',
    projectId: 'finanzas-d8536',
    databaseURL: 'https://finanzas-d8536-default-rtdb.firebaseio.com',
    storageBucket: 'finanzas-d8536.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZKQtnGa3aLO4__pVEPQuaDsQ6ek2U7MI',
    appId: '1:148369501195:ios:5d0072adb76f63f2e16b0e',
    messagingSenderId: '148369501195',
    projectId: 'finanzas-d8536',
    databaseURL: 'https://finanzas-d8536-default-rtdb.firebaseio.com',
    storageBucket: 'finanzas-d8536.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZKQtnGa3aLO4__pVEPQuaDsQ6ek2U7MI',
    appId: '1:148369501195:ios:5d0072adb76f63f2e16b0e',
    messagingSenderId: '148369501195',
    projectId: 'finanzas-d8536',
    databaseURL: 'https://finanzas-d8536-default-rtdb.firebaseio.com',
    storageBucket: 'finanzas-d8536.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkFxwu_Kzn0gB1E5sk6ZcymcH09yPJ2bA',
    appId: '1:148369501195:web:6341a15fa785433fe16b0e',
    messagingSenderId: '148369501195',
    projectId: 'finanzas-d8536',
    authDomain: 'finanzas-d8536.firebaseapp.com',
    databaseURL: 'https://finanzas-d8536-default-rtdb.firebaseio.com',
    storageBucket: 'finanzas-d8536.firebasestorage.app',
  );
}
